Repository Upjuyanolja/Upjuyanolja_FE, pull requests merged in 2024-01, with the labels that each got.

#30 Setting: router 설정
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.MD
  package-lock.json
  package.json
  src/App.tsx
  src/layout.tsx
  src/pages/.gitkeep
  src/pages/coupon-registration/index.tsx
  src/pages/coupon/index.tsx
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
  src/pages/init/index.tsx
  src/pages/main/index.tsx
  src/pages/point-detail/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
  src/pages/room/index.tsx
  src/pages/sign-in-agreement/index.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up-success/index.tsx
  src/pages/sign-up/index.tsx
Labels: Feat

#32 Setting: SCSS 초기 세팅 완료
  src/App.tsx
  src/index.tsx
  src/styles/abstracts/_functions.scss
  src/styles/abstracts/_mixins.scss
  src/styles/abstracts/_variables.scss
  src/styles/base/_global.scss
  src/styles/base/_typography.scss
  src/styles/style.scss
Labels: Feat

#33 Fix: antd 적용 문제 해결
  craco.config.js
  package.json
  src/layout.tsx
Labels: Fix

#39 Test: 로그인 / 회원 가입 공통 푸터 테스트 코드
  .babelrc
  src/test/layouts/footer/footer.test.tsx
  src/test/layouts/footer/index.tsx
Labels: Test

#43 Feat: styled components install
  package-lock.json
  package.json
  src/index.css
  src/index.tsx
  src/pages/main/index.tsx
  src/styles/abstracts/_functions.scss
  src/styles/abstracts/_mixins.scss
  src/styles/abstracts/_variables.scss
  src/styles/base/_global.scss
  src/styles/base/_typography.scss
  src/styles/style.scss
Labels: Style

#44 Test: 회원 정보 완료 페이지 테스트 코드
  .babelrc
  src/hooks/sign-up/useSignUp.ts
  src/test/layouts/footer/Footer.test.tsx
  src/test/sign-up-success/SignUpSuccess.test.tsx
  src/test/sign-up-success/index.tsx
Labels: Test

#45 Style: modal , button 공통 style 지정
  public/index.html
  src/index.css
Labels: Style

#46 Style: antd 공통 커스텀
  src/index.css
Labels: Style

#37 Style: 사이드바 퍼블리싱
  package-lock.json
  package.json
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/accommodation-list/type.ts
  src/components/layout/side-bar/index.tsx
  src/components/layout/side-bar/navigation/index.tsx
  src/components/layout/side-bar/navigation/type.ts
  src/components/layout/side-bar/signout-btn/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/layout/side-bar/user-profile/type.ts
  src/components/text-box/index.tsx
  src/components/text-box/type.ts
  src/constants/colors/index.ts
  src/constants/colors/type.ts
  src/constants/navigation/index.ts
  src/layout.tsx
Labels: Style

#35 Feat: 숙소 등록하기 버튼 페이지 퍼블리싱
  package-lock.json
  package.json
  src/pages/init/index.tsx
Labels: Feat, Style

#51 Feat: 회원 정보 완료 페이지 구현
  src/assets/image/logo.png
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/navigation/index.tsx
  src/components/layout/side-bar/signout-btn/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/sign-up/index.tsx
  src/pages/sign-up-success/index.tsx
Labels: Feat, Style

#50 Feat: main page 퍼블리싱
  package-lock.json
  package.json
  src/assets/.gitkeep
  src/assets/image/mainCoinImage.png
  src/assets/image/mainPromotionImage.png
  src/assets/image/mainPromotionImage2.png
  src/components/.gitkeep
  src/components/main/main-chart/index.tsx
  src/components/main/main-coupon-status-container/index.tsx
  src/components/main/main-navigation-container/index.tsx
  src/index.css
  src/pages/main/index.tsx
Labels: Feat, Style

#61 Chore: TextBox 컴포넌트 cursor 기본 값 삭제
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/navigation/index.tsx
  src/components/layout/side-bar/signout-btn/index.tsx
  src/components/text-box/index.tsx
Labels: Feat

#62 Style: 쿠폰 발급 페이지 퍼블리싱
  src/components/coupon-registration/coupon-applier/common-quantity-coupon-setter/index.tsx
  src/components/coupon-registration/coupon-applier/index.tsx
  src/components/coupon-registration/coupon-applier/room-coupon-applier/index.tsx
  src/components/coupon-registration/coupon-card/index.tsx
  src/components/coupon-registration/coupon-card/type.ts
  src/components/coupon-registration/coupon-type/index.tsx
  src/components/coupon-registration/coupon-type/type.ts
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/accommodation-list/type.ts
  src/components/layout/side-bar/navigation/index.tsx
  src/components/layout/side-bar/navigation/type.ts
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/layout/side-bar/user-profile/type.ts
  src/components/spacing/index.tsx
  src/components/spacing/type.ts
  src/pages/coupon-registration/index.tsx
Labels: Style

#60 Test: 서비스 이용 동의 페이지 테스트 코드 구현
  src/pages/sign-up-success/index.tsx
  src/test/sign-in-agreement/SignInAgreement.test.tsx
  src/test/sign-in-agreement/index.tsx
Labels: Test

#65 Style: 쿠폰 미리보기 컴포넌트 퍼블리싱
  src/components/coupon-registration/coupon-preview/coupoin-preview-item/index.tsx
  src/components/coupon-registration/coupon-preview/coupoin-preview-item/type.ts
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/spacing/index.tsx
  src/components/spacing/type.ts
  src/pages/coupon-registration/index.tsx
Labels: Style

#66 Fix: jest 오류 수정
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/App.test.tsx
  src/mocks/fileMock.js
  src/setupTest.ts
  src/setupTests.ts
  src/test/main/Main.test.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: Fix, Error

#64 Feat: 서비스 이용 동의 페이지 구현
  src/components/sign-up/index.tsx
  src/pages/sign-in-agreement/index.tsx
  src/pages/sign-up-success/index.tsx
Labels: Feat, Style

#52 Feat: 최초 숙소 등록 페이지 퍼블리싱
  src/App.tsx
  src/assets/image/grayGuestHouse.png
  src/assets/image/grayHotel_resort.png
  src/assets/image/grayMotel.png
  src/assets/image/grayPension_pool.png
  src/assets/image/primaryGuestHouse.png
  src/assets/image/primaryHotel_resort.png
  src/assets/image/primaryMotel.png
  src/assets/image/primaryPension_pool.png
  src/components/init-registration/AccommodationAddress.tsx
  src/components/init-registration/AccommodationCategory.tsx
  src/components/init-registration/AccommodationDesc.tsx
  src/components/init-registration/AccommodationName.tsx
  src/components/init-registration/RadioButtonCustomContainer.tsx
  src/components/init-registration/type.ts
  src/components/init/ButtonContainer.tsx
  src/components/init/CheckBoxContainer.tsx
  src/components/init/FormErrorMessage.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/InitLayout.tsx
  src/components/init/type.ts
  src/pages/init-accommodation-registration/index.tsx
Labels: Feat, Style

#49 Feat: 포인트 충전 모달
  src/components/modal/point/info-container/index.tsx
  src/components/modal/point/point-modal/index.tsx
  src/components/modal/point/point-modal/types.ts
  src/pages/point-detail/index.tsx
  src/test/modal/point/PointModal.test.tsx
  src/test/modal/point/index.tsx
  src/utils/Format/numberFormat.ts
Labels: Feat, Style

#63 Test: main page 테스트 코드 구현
  jest.config.js
  jsdom-extended.js
  public/data/.gitkeep
  public/data/main/staticsData.json
  src/components/main/main-chart/index.tsx
  src/mocks/browsers.ts
  src/mocks/server.ts
  src/pages/main/index.tsx
  src/setupTest.ts
  src/test/.gitkeep
  src/test/main/Main.test.tsx
  src/utils/.gitkeep
Labels: Test

#90 Feat: main page api 구현
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/assets/data/revenueData.json
  src/assets/data/staticsData.json
  src/components/main/main-chart/index.tsx
  src/components/main/main-chart/type.ts
  src/components/main/main-coupon-status-container/index.tsx
  src/components/main/main-coupon-status-container/type.ts
  src/components/main/main-navigation-container/index.tsx
  src/components/main/main-navigation-container/type.ts
  src/hooks/.gitkeep
  src/hooks/main/useMain.ts
  src/index.tsx
  src/mocks/browsers.ts
  src/mocks/coupon/index.ts
  src/mocks/handlers.ts
  src/pages/main/index.tsx
  src/queries/coupon/index.ts
  src/test/main/Main.test.tsx
  src/types/.gitkeep
  src/types/api.ts
Labels: Feat

#91 Test: 최초 숙소 등록 페이지 테스트 코드 구현
  src/App.tsx
  src/components/init/ButtonContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationAddress.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/RadioButtonCustomContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/init-button/InitLayout.tsx
  src/components/init/init-button/type.ts
  src/components/init/type.ts
  src/constants/init/index.ts
  src/constants/init/init-accommodation-registration/index.ts
  src/pages/init-accommodation-registration/index.tsx
  src/test/init/ButtonContainer.test.tsx
  src/test/init/ImageUploadContainer.test.tsx
  src/test/init/NameContainer.test.tsx
  src/test/init/init-accommodation-registration/InitAccommodationRegistration.test.tsx
  src/test/matchMedia.mock
Labels: Test

#57 Style: 객실 관리 페이지 퍼블리싱
  src/App.tsx
  src/assets/image/coupon.svg
  src/components/room/room-card/index.tsx
  src/constants/routes.ts
  src/pages/room-management/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room/index.tsx
Labels: Feat, Style

#97 Fix: main test 에러 해결
  src/components/main/main-coupon-status-container/index.tsx
  src/index.css
  src/test/main/Main.test.tsx
Labels: Fix

#96 Style: 결제 영수증, 취소 요청 모달 퍼블리싱
  src/components/modal/payment/cancel/index.tsx
  src/components/modal/payment/common/company-info/index.tsx
  src/components/modal/payment/common/coupon-info/index.tsx
  src/components/modal/payment/common/order-info/index.tsx
  src/components/modal/payment/common/order-point-info/index.tsx
  src/components/modal/payment/common/order-point-info/types.tsx
  src/components/modal/payment/receipt/index.tsx
  src/pages/point-detail/index.tsx
Labels: Style

#81 Test: 로그인 페이지 테스트 코드 구현
  jest.config.js
  jsdom-extended.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/sign-in/index.ts
  src/api/sign-in/type.ts
  src/assets/data/accomodationsData.json
  src/assets/data/signInData.json
  src/components/modal/payment/common/order-point-info/index.tsx
  src/components/modal/payment/common/order-point-info/types.tsx
  src/hooks/sign-in/useSignIn.ts
  src/index.css
  src/mocks/fileMock.js
  src/mocks/handlers.ts
  src/mocks/sign-in/index.ts
  src/pages/sign-in-agreement/index.tsx
  src/pages/sign-up/index.tsx
  src/queries/sign-in/index.ts
  src/test/layouts/footer/Footer.test.tsx
  src/test/sign-in-agreement/SignInAgreement.test.tsx
  src/test/sign-in/SignIn.test.tsx
  src/test/sign-in/index.tsx
  src/test/sign-up-success/SignUpSuccess.test.tsx
  src/types/apis.ts
  src/utils/sign-in/ValidateSchema.ts
Labels: Test

#100 Feat: 최초 숙소 등록 페이지 비즈니스 코드 구현 전 기획 변경에 의한 수정
  package-lock.json
  package.json
  src/components/init/ButtonContainer.tsx
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationAddress.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/type.ts
  src/constants/init/init-accommodation-registration/index.ts
  src/index.css
  src/pages/init-accommodation-registration/index.tsx
  src/pages/room-registration/index.tsx
  src/test/init/ImageUploadContainer.test.tsx
  src/test/init/NameContainer.test.tsx
  src/test/init/init-accommodation-registration/InitAccommodationRegistration.test.tsx
Labels: Feat, Refactor, Test

#101 Style: 쿠폰 관리 페이지 퍼블리싱
  package-lock.json
  package.json
  src/assets/image/smallLogo.svg
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-status-tag/index.tsx
  src/components/coupon/coupon-status-tag/type.ts
  src/constants/colors/index.ts
  src/index.css
  src/pages/coupon/index.tsx
  src/pages/coupon/type.ts
Labels: Style

#106 Style: 포인트 내역 페이지 퍼블리싱
  src/components/point-charge-modal/info-container/index.tsx
  src/components/point-charge-modal/point-modal/index.tsx
  src/components/point-charge-modal/point-modal/types.ts
  src/components/point-detail/badge/index.tsx
  src/components/point-detail/badge/types.ts
  src/components/point-detail/index.tsx
  src/components/point-detail/page/index.tsx
  src/components/point-detail/payment/cancel/index.tsx
  src/components/point-detail/payment/common/company-info/index.tsx
  src/components/point-detail/payment/common/coupon-info/index.tsx
  src/components/point-detail/payment/common/order-info/index.tsx
  src/components/point-detail/payment/common/order-point-info/index.tsx
  src/components/point-detail/payment/common/order-point-info/types.tsx
  src/components/point-detail/payment/receipt/index.tsx
  src/components/point-detail/point-box/index.tsx
  src/components/point-detail/point-detail-list/index.tsx
  src/components/point-detail/point-detail-menu/index.tsx
  src/constants/colors/index.ts
  src/pages/point-detail/index.tsx
Labels: Style

#109 Feat: 사이드바 비지니스 로직 구현
  src/api/accommodation/index.ts
  src/api/accommodation/type.ts
  src/api/member/index.ts
  src/api/member/type.ts
  src/api/point/index.ts
  src/api/point/type.ts
  src/assets/data/accommodationsData.json
  src/assets/data/pointSummaryData.json
  src/assets/data/userInfoData.json
  src/components/coupon-registration/coupon-preview/coupon-preview-item/index.tsx
  src/components/coupon-registration/coupon-preview/coupon-preview-item/type.ts
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/accommodation-list/type.ts
  src/components/layout/side-bar/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/layout/side-bar/user-profile/type.ts
  src/hooks/side-bar/useSideBar.ts
  src/mocks/accommodation/index.ts
  src/mocks/handlers.ts
  src/mocks/member/index.ts
  src/mocks/point/index.ts
  src/mocks/sign-in/index.ts
  src/queries/accommodation/index.ts
  src/queries/member/index.ts
  src/queries/point/index.ts
  src/test/sign-in/SignIn.test.tsx
  src/utils/Format/numberFormat.ts
Labels: Feat

#58 Test: Sidebar 테스트 코드 작성
  src/components/layout/side-bar/user-profile/index.tsx
  src/test/layouts/side-bar/SideBar.test.tsx
Labels: Test

#111 Feat: error code 상수 분리
  src/constants/api/index.ts
Labels: Feat

#103 Feat: 로그인 페이지 구현
  src/api/sign-in/index.ts
  src/components/layout/footer/index.tsx
  src/components/sign-up/index.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
  src/test/sign-in/index.tsx
Labels: Feat, Style

#99 Feat: 객실 추가 페이지 퍼블리싱 및 컴포넌트 생성
  src/components/room/capacity-container/index.tsx
  src/components/room/capacity-container/type.ts
  src/components/room/num-of-rooms-container/index.tsx
  src/components/room/num-of-rooms-container/type.ts
  src/components/room/price-container/index.tsx
  src/components/room/price-container/type.ts
  src/components/room/time-container/index.tsx
  src/components/room/time-container/type.ts
  src/constants/room/room-registration/index.ts
  src/pages/room-registration/index.tsx
Labels: Feat, Style

#114 Feat: 최초 숙소 등록 페이지 비즈니스 코드 구현
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationAddress.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/RadioButtonCustomContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/type.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/room-registration/index.tsx
  src/stores/init/atoms.ts
  src/test/init/ImageUploadContainer.test.tsx
  src/test/init/NameContainer.test.tsx
  src/test/init/init-accommodation-registration/InitAccommodationRegistration.test.tsx
Labels: Feat

#119 Feat: 쿠폰 관리 페이지 조회 api 구현
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/assets/data/couponData.json
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-header/type.ts
  src/components/coupon/coupon-status-tag/index.tsx
  src/components/coupon/table-cell/index.tsx
  src/components/coupon/table-cell/type.ts
  src/components/coupon/table/index.tsx
  src/components/coupon/table/type.ts
  src/constants/coupon/index.ts
  src/constants/date/index.ts
  src/hooks/coupon/useCoupon.ts
  src/mocks/coupon/index.ts
  src/mocks/handlers.ts
  src/pages/coupon/index.tsx
  src/pages/coupon/type.ts
  src/queries/coupon/index.ts
Labels: Feat

#116 Feat: 쿠폰 발급 페이지 비지니스 로직 코드 구현
  src/App.tsx
  src/components/coupon-registration/coupon-type/index.tsx
  src/constants/coupon/index.ts
  src/hooks/coupon-registration/useCouponRegistrationProvider.tsx
  src/hooks/side-bar/useSideBar.ts
Labels: Feat

#121 Feat: 레이아웃 커스텀 작업 및 기획 변경으로 인한 객실 컴포넌트 수정
  src/App.tsx
  src/components/room/capacity-container/index.tsx
  src/components/room/num-of-rooms-container/index.tsx
  src/components/room/price-container/index.tsx
  src/components/room/room-buttons/index.tsx
  src/components/room/room-buttons/type.ts
  src/components/room/room-layout/index.tsx
  src/components/room/room-layout/type.ts
  src/components/room/time-container/index.tsx
  src/constants/navigation/index.ts
  src/layout.tsx
  src/pages/room-registration/index.tsx
Labels: Feat, Style

#125 Feat: Toss Payments 연동
  .gitignore
  package-lock.json
  package.json
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/point-charge-modal/point-modal/index.tsx
Labels: Feat

#126 Style: 등록 정보 확인 페이지 퍼블리싱
  src/components/init/ButtonContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/RadioButtonCustomContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/init-button/InitLayout.tsx
  src/components/init/init-info-confirmation/AccommodationInfo.tsx
  src/components/init/init-info-confirmation/CustomButton.tsx
  src/components/init/init-info-confirmation/ImageCarousel.tsx
  src/components/init/init-info-confirmation/RoomInfo.tsx
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/components/init/init-info-confirmation/type.ts
  src/index.css
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
Labels: Style

#134 Feat: point-detail 상세페이지 테스트 및 비지니스 로직 구현
  src/api/point-detail/get-point-detail/index.ts
  src/api/point-detail/get-point-detail/type.ts
  src/assets/data/pointDetailChargesData.json
  src/assets/data/pointDetailData.json
  src/assets/data/pointDetailUsageData.json
  src/components/point-charge-modal/point-modal/index.tsx
  src/components/point-detail/badge/index.tsx
  src/components/point-detail/badge/types.ts
  src/components/point-detail/index.tsx
  src/components/point-detail/page/index.tsx
  src/components/point-detail/point-box/index.tsx
  src/components/point-detail/point-detail-list/index.tsx
  src/components/point-detail/point-detail-menu/index.tsx
  src/hooks/point-detail/index.tsx
  src/mocks/handlers.ts
  src/mocks/point-detail/index.ts
  src/pages/point-detail/index.tsx
  src/queries/point-detail/index.ts
  src/stores/point-detail/atoms.ts
  src/test/modal/point/PointModal.test.tsx
  src/test/point-detail/PointDetail.test.tsx
  src/utils/isNumber.ts
Labels: Feat, Test

#129 Feat: coupon form 로직 구현
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-header/type.ts
  src/components/coupon/table-cell/index.tsx
  src/components/coupon/table-cell/type.ts
  src/components/coupon/table/index.tsx
  src/components/coupon/table/type.ts
  src/hooks/coupon/useCoupon.ts
  src/hooks/coupon/useCouponForm.ts
  src/pages/coupon/index.tsx
  src/utils/input/keyboard.ts
Labels: Feat

#132 Test: 등록 확인 페이지 테스트 코드 구현
  src/components/init/ButtonContainer.tsx
  src/components/init/init-info-confirmation/CustomButton.tsx
  src/components/init/type.ts
  src/pages/init-info-confirmation/index.tsx
  src/test/init/init-info-confirmation/InitInfoConfirmation.test.tsx
  src/test/init/init-info-confirmation/WelcomModalForTest.tsx
Labels: Test

#130 Feat: 객실 컴포넌트 Form 적용 및 디버깅
  src/components/init/NameContainer.tsx
  src/components/room/capacity-container/index.tsx
  src/components/room/capacity-container/type.ts
  src/components/room/num-of-rooms-container/index.tsx
  src/components/room/num-of-rooms-container/type.ts
  src/components/room/price-container/index.tsx
  src/components/room/price-container/type.ts
  src/components/room/time-container/index.tsx
  src/components/room/time-container/type.ts
  src/index.css
  src/pages/room-registration/index.tsx
Labels: Fix, Feat

#137 Style: 기획, 디자인 변경에 따른 init 플로우 수정
  src/App.tsx
  src/components/init/ButtonContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/init-info-confirmation/AccommodationInfo.tsx
  src/components/init/type.ts
  src/components/layout/init-layout/InitLayout.tsx
  src/components/layout/init-layout/type.ts
  src/pages/init-accommodation-registration/index.tsx
  src/stores/init/atoms.ts
Labels: Style, Refactor

#122 Style: 최초 객실 등록 페이지 퍼블리싱
  src/components/init/FormErrorMessage.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationAddress.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/type.ts
  src/components/room/capacity-container/index.tsx
  src/components/room/num-of-rooms-container/index.tsx
  src/components/room/num-of-rooms-container/type.ts
  src/components/room/price-container/index.tsx
  src/components/room/time-container/index.tsx
  src/index.css
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-room-registration/index.tsx
  src/pages/room-registration/index.tsx
Labels: Style

#145 Feat: router 변경
  src/App.tsx
  src/constants/api/index.ts
  src/constants/routes.ts
  src/hooks/main/useMain.ts
  src/pages/main-redirect/index.tsx
Labels: Feat

#142 Feat: 쿠폰 관리 페이지 수정 삭제 기능 구현
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/api/sign-in/index.ts
  src/assets/data/couponData.json
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-header/type.ts
  src/components/coupon/table-cell/index.tsx
  src/components/coupon/table/index.tsx
  src/hooks/coupon/type.ts
  src/hooks/coupon/useCoupon.ts
  src/hooks/coupon/useCouponForm.ts
  src/index.css
  src/mocks/coupon/index.ts
  src/mocks/handlers.ts
  src/pages/coupon/index.tsx
  src/queries/coupon/index.ts
  src/types/apis.ts
Labels: Feat

#144 Test: 회원 가입 페이지 테스트 코드 구현
  src/api/sign-in/index.ts
  src/api/sign-in/type.ts
  src/api/sign-up/index.ts
  src/api/sign-up/type.ts
  src/assets/data/failRequestGetData1.json
  src/assets/data/failRequestGetData2.json
  src/assets/data/failRequestPostData1.json
  src/assets/data/failRequestPostData2.json
  src/assets/data/requestAuthenticationData.json
  src/assets/data/signUpData.json
  src/assets/data/verifyAuthenticationData.json
  src/hooks/sign-in/useSignIn.ts
  src/index.css
  src/mocks/handlers.ts
  src/mocks/sign-up/index.ts
  src/pages/init/index.tsx
  src/pages/sign-in/index.tsx
  src/queries/sign-in/index.ts
  src/queries/sign-up/index.ts
  src/test/sign-in/SignIn.test.tsx
  src/test/sign-in/index.tsx
  src/test/sign-up/SignUp.test.tsx
  src/test/sign-up/index.tsx
  src/utils/sign-up/ValidateSchema.ts
Labels: Test

#150 Feat: (최초) 객실 등록 페이지 비즈니스 코드 작성
  src/components/init/ButtonContainer.tsx
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
Labels: Feat

#127 Feat: 쿠폰 발급 페이지 비지니스 코드 작성
  .gitignore
  src/App.tsx
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/api/member/index.ts
  src/api/member/type.ts
  src/assets/data/couponRoomListData.json
  src/components/coupon-registration/coupon-applier/common-quantity-coupon-setter/index.tsx
  src/components/coupon-registration/coupon-applier/index.tsx
  src/components/coupon-registration/coupon-applier/room-coupon-applier/index.tsx
  src/components/coupon-registration/coupon-applier/room-coupon-applier/type.ts
  src/components/coupon-registration/coupon-preview/coupon-preview-item/index.tsx
  src/components/coupon-registration/coupon-preview/coupon-preview-item/type.ts
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/coupon-registration/coupon-preview/type.ts
  src/components/coupon-registration/coupon-type/index.tsx
  src/components/coupon-registration/coupon-type/type.ts
  src/components/coupon-registration/discount-type/index.tsx
  src/components/coupon-registration/type.ts
  src/components/layout/side-bar/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/layout/side-bar/user-profile/type.ts
  src/constants/coupon-registration/index.ts
  src/constants/coupon-registration/type.ts
  src/constants/coupon/index.ts
  src/constants/navigation/index.ts
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/hooks/coupon-registration/useCouponRegistrationProvider.tsx
  src/hooks/side-bar/useSideBar.ts
  src/mocks/coupon-registration/index.ts
  src/mocks/handlers.ts
  src/mocks/member/index.ts
  src/pages/coupon-registration/index.tsx
  src/queries/coupon-registration/index.ts
  src/queries/member/index.ts
  src/stores/coupon-registration/atoms.ts
  src/types/event.ts
  src/types/setState.ts
  src/utils/is-number/index.ts
  src/utils/keydown/handleEnterKeyDown.ts
Labels: Feat

#154 Feat: (최초) 객실 등록 페이지 비즈니스 코드 구현
  src/components/init/ButtonContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/type.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
Labels: Feat

#153 Feat: 추가 구매 모달 로직 구현
  src/assets/data/couponData.json
  src/components/coupon/additional-purchase-content/index.tsx
  src/components/coupon/additional-purchase-content/type.ts
  src/components/coupon/additional-purchase-footer/index.tsx
  src/components/coupon/additional-purchase-footer/type.ts
  src/components/coupon/additional-purchase-info/index.tsx
  src/components/coupon/additional-purchase-info/type.ts
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-header/type.ts
  src/components/coupon/table-cell/index.tsx
  src/components/coupon/table-cell/type.ts
  src/components/coupon/table/index.tsx
  src/components/coupon/table/type.ts
  src/constants/coupon/index.ts
  src/hooks/coupon/type.ts
  src/hooks/coupon/useCoupon.ts
  src/index.css
  src/pages/coupon/index.tsx
  src/utils/discountCoupon.ts
  src/utils/input/keyboard.ts
Labels: Feat

#160 Feat: 토스 로직, 토스트 추가
  src/App.tsx
  src/api/toss/index.ts
  src/api/toss/type.ts
  src/assets/data/pointChargeData.json
  src/components/point-charge-modal/point-modal/index.tsx
  src/constants/navigation/index.ts
  src/constants/routes.ts
  src/mocks/handlers.ts
  src/mocks/point/index.ts
  src/pages/toss-fail/index.tsx
  src/pages/toss-success/index.tsx
  src/queries/point-charge-modal/index.tsx
  src/queries/point-detail/index.ts
  src/stores/point-charge-modal/index.ts
Labels: Fix, Feat

#161 Feat: main 변경된 로직 수정
  src/App.tsx
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/assets/data/revenueData.json
  src/assets/data/staticsData.json
  src/assets/image/mainPromotionImage.png
  src/assets/image/mainPromotionImage2.png
  src/assets/image/mainWomanImage.png
  src/components/main/coupon-navigation-container/index.tsx
  src/components/main/coupon-navigation-container/type.ts
  src/components/main/main-chart/index.tsx
  src/components/main/main-chart/type.ts
  src/components/main/main-coupon-status-container/index.tsx
  src/components/main/main-navigation-container/type.ts
  src/components/main/user-guide-navigation-container/index.tsx
  src/components/main/user-guide-navigation-container/type.ts
  src/constants/routes.ts
  src/hooks/main/useMain.ts
  src/index.css
  src/mocks/handlers.ts
  src/pages/main/index.tsx
  src/pages/user-guide/index.tsx
  src/queries/coupon/index.ts
Labels: Feat

#158 Feat: 쿠폰 발급 페이지 비지니스 코드 작성
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/assets/data/buyCouponData.json
  src/assets/data/failBuyCouponData.json
  src/components/coupon-registration/coupon-applier/common-quantity-coupon-setter/index.tsx
  src/components/coupon-registration/coupon-applier/room-coupon-applier/index.tsx
  src/components/coupon-registration/coupon-preview/coupon-preview-item/index.tsx
  src/components/coupon-registration/coupon-preview/coupon-preview-item/type.ts
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/coupon-registration/discount-type/index.tsx
  src/components/coupon-registration/type.ts
  src/constants/navigation/index.ts
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/mocks/coupon-registration/index.ts
  src/mocks/handlers.ts
  src/pages/coupon-registration/index.tsx
  src/queries/coupon-registration/index.ts
  src/stores/coupon-registration/atoms.ts
  src/utils/discountCoupon.ts
Labels: Feat

#151 Feat: 객실 컴포넌트 수정 및 추가하기 페이지 API 연결
  src/api/room/index.ts
  src/api/room/type.ts
  src/assets/data/roomData.json
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/room/capacity-container/index.tsx
  src/components/room/price-container/index.tsx
  src/components/room/type.ts
  src/constants/room/room-registration/index.ts
  src/hooks/room/useAddRoom.ts
  src/mocks/handlers.ts
  src/mocks/room/index.ts
  src/pages/room-registration/index.tsx
  src/queries/room/index.ts
Labels: Feat

#163 Feat: 추가 구매 api 구현
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/components/coupon/additional-purchase-content/index.tsx
  src/components/coupon/additional-purchase-content/type.ts
  src/components/coupon/additional-purchase-footer/index.tsx
  src/components/coupon/additional-purchase-footer/type.ts
  src/components/coupon/additional-purchase-info/index.tsx
  src/components/coupon/additional-purchase-info/type.ts
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/table-cell/index.tsx
  src/components/coupon/table/index.tsx
  src/hooks/coupon/type.ts
  src/hooks/coupon/useCoupon.ts
  src/index.css
  src/mocks/coupon/index.ts
  src/mocks/handlers.ts
  src/pages/coupon/index.tsx
  src/queries/coupon/index.ts
  src/types/api.ts
Labels: Feat

#167 Chore: 이용 가이드 및 프로모션 이미지 수정
  public/favicon.ico
  public/index.html
  src/assets/image/mainPromotionImage.jpg
  src/assets/image/mainPromotionImage.png
  src/assets/image/mainWomanImage.png
  src/components/main/main-chart/index.tsx
  src/components/main/user-guide-navigation-container/index.tsx
  src/hooks/main/useMain.ts
  src/pages/main/index.tsx
Labels: Chore

#159 Feat: 등록 확인 페이지 비즈니스 코드 작성
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-info-confirmation/AccommodationInfo.tsx
  src/components/init/init-info-confirmation/ImageCarousel.tsx
  src/components/init/init-info-confirmation/RoomInfo.tsx
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/components/init/init-info-confirmation/type.ts
  src/components/layout/init-layout/InitLayout.tsx
  src/components/room/capacity-container/index.tsx
  src/components/room/num-of-rooms-container/index.tsx
  src/components/room/price-container/index.tsx
  src/constants/init/index.ts
  src/index.css
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
  src/stores/room/atoms.ts
  src/test/init/init-accommodation-registration/InitAccommodationRegistration.test.tsx
Labels: Feat

#156 Feat: 회원 가입 페이지 구현
  src/constants/api/index.ts
  src/mocks/sign-up/index.ts
  src/pages/sign-in-agreement/index.tsx
  src/pages/sign-up/index.tsx
  src/test/sign-up/index.tsx
Labels: Feat, Style

#176 Feat: 약관 구현 및 쿠폰 없을 때 화면 구현
  src/assets/data/failBuyCouponData.json
  src/assets/image/mainCoinImage.png
  src/components/agreement-modal/coupon-agreement-modal/index.tsx
  src/components/agreement-modal/point-agreement-modal/index.tsx
  src/components/agreement-modal/type.ts
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/coupon/additional-purchase-content/index.tsx
  src/components/coupon/additional-purchase-footer/index.tsx
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/not-found-coupon/index.tsx
  src/components/main/coupon-navigation-container/index.tsx
  src/components/main/main-chart/index.tsx
  src/components/main/main-coupon-status-container/index.tsx
  src/components/point-charge-modal/point-modal/index.tsx
  src/constants/navigation/index.ts
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/hooks/coupon/useCoupon.ts
  src/index.css
  src/layout.tsx
  src/mocks/coupon/index.ts
  src/pages/coupon/index.tsx
  src/pages/room-registration/index.tsx
Labels: Feat

#168 Style: 객실 수정하기 페이지 퍼블리싱/관리하기 API 연결
  src/App.tsx
  src/api/room/index.ts
  src/api/room/type.ts
  src/assets/data/roomListData.json
  src/components/init/ButtonContainer.tsx
  src/components/room/room-buttons/index.tsx
  src/components/room/room-buttons/type.ts
  src/components/room/room-layout/index.tsx
  src/components/room/status-container/index.tsx
  src/hooks/room/useAddRoom.ts
  src/layout.tsx
  src/mocks/handlers.ts
  src/mocks/room/index.ts
  src/pages/room-management/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
  src/queries/room/index.ts
Labels: Feat, Style

#173 Feat: 숙소 등록 페이지 비즈니스코드 작성
  src/api/init/index.ts
  src/api/init/type.ts
  src/assets/data/failPostImageFileData.json
  src/assets/data/postAccommodationData.json
  src/assets/data/postImageFileData.json
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/NameContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/AccommodationDesc.tsx
  src/components/init/init-info-confirmation/AccommodationInfo.tsx
  src/components/init/init-info-confirmation/RoomInfo.tsx
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/components/init/type.ts
  src/components/layout/init-layout/InitLayout.tsx
  src/mocks/handlers.ts
  src/mocks/init/index.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
  src/pages/init/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
  src/queries/init/index.ts
  src/stores/init/atoms.ts
Labels: Feat

#178 Feat: 등록 정보 확인하기 페이지 - 객실, 숙소 수정
  src/api/room/type.ts
  src/components/init/ButtonContainer.tsx
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/components/init/type.ts
  src/components/room/capacity-container/index.tsx
  src/components/room/price-container/index.tsx
  src/components/room/time-container/index.tsx
  src/components/room/time-container/type.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
  src/stores/init/type.ts
Labels: Feat

#177 Feat: interceptor 구현 및 퍼블리싱 수정
  src/api/index.ts
  src/api/index.tsx
  src/api/sign-in/index.ts
  src/mocks/handlers.ts
  src/pages/sign-in-agreement/index.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up-success/index.tsx
  src/pages/sign-up/index.tsx
Labels: Fix, Feat

#180 Test: 쿠폰 관리 페이지 테스트 코드 구현
  public/favicon.ico
  src/assets/image/additionalBuyLogo.png
  src/assets/image/smallLogo.svg
  src/components/coupon/additional-purchase-content/index.tsx
  src/components/coupon/additional-purchase-info/index.tsx
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-status-tag/index.tsx
  src/components/coupon/table-cell/index.tsx
  src/components/coupon/table/index.tsx
  src/mocks/handlers.ts
  src/setupTest.ts
  src/test/coupon/Coupon.test.tsx
  src/test/matchMedia.mock
Labels: Test

#179 Feat: 등록 확인 페이지 비즈니스 코드 작성
  src/components/init/ButtonContainer.tsx
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/init-accommodation-registration/AccommodationCategory.tsx
  src/components/init/init-accommodation-registration/RadioButtonCustomContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/init-info-confirmation/AccommodationInfo.tsx
  src/components/init/init-info-confirmation/RoomInfo.tsx
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/components/init/type.ts
  src/components/layout/init-layout/InitLayout.tsx
  src/components/room/price-container/index.tsx
  src/components/room/price-container/type.ts
  src/index.css
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
Labels: Feat

#172 Feat: 쿠폰 발급 페이지 API 연결 및 에러 핸들링
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/components/coupon-registration/coupon-applier/common-quantity-coupon-setter/index.tsx
  src/components/coupon-registration/coupon-applier/index.tsx
  src/components/coupon-registration/coupon-applier/room-coupon-applier/index.tsx
  src/components/coupon-registration/coupon-applier/type.ts
  src/components/coupon-registration/coupon-preview/coupon-preview-item/index.tsx
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/coupon-registration/type.ts
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/accommodation-list/type.ts
  src/components/layout/side-bar/index.tsx
  src/components/layout/side-bar/navigation/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/layout/side-bar/user-profile/type.ts
  src/constants/api/index.ts
  src/constants/navigation/index.ts
  src/constants/routes.ts
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/hooks/side-bar/useSideBar.ts
  src/hooks/sign-in/useSignIn.ts
  src/mocks/coupon-registration/index.ts
  src/mocks/handlers.ts
  src/pages/coupon-registration/index.tsx
  src/pages/point-detail/index.tsx
  src/queries/coupon-registration/index.ts
  src/stores/coupon-registration/atoms.ts
Labels: Feat

#189 Feat: 포인트 상세 관련 디자인 변경, API 명세서 변경
  src/api/point-detail/get-point-detail/type.ts
  src/assets/data/pointDetailData.json
  src/components/agreement-modal/point-agreement-modal/index.tsx
  src/components/point-detail/payment/common/coupon-info/index.tsx
  src/components/point-detail/payment/common/order-info/index.tsx
  src/components/point-detail/payment/receipt/index.tsx
  src/components/point-detail/point-box/index.tsx
  src/components/point-detail/point-detail-list/index.tsx
  src/mocks/handlers.ts
  src/pages/point-detail/index.tsx
  src/stores/point-charge-modal/index.ts
  src/stores/point-detail/atoms.ts
Labels: Feat, Style

#192 Feat: 이용 가이드 및 모바일 화면 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/image/pcImage.png
  src/assets/image/pdfLogo.svg
  src/assets/image/userGuideAccommodation.png
  src/assets/image/userGuideCoupon.png
  src/assets/image/userGuideHome.png
  src/assets/image/userGuidePoint.png
  src/index.tsx
  src/pages/mobile/index.tsx
  src/pages/user-guide/index.tsx
Labels: Feat

#190 Style: 사이드바 반응형 제작
  src/api/coupon/index.ts
  src/assets/data/accommodationsData.json
  src/components/coupon-registration/coupon-applier/room-coupon-applier/index.tsx
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/index.tsx
  src/components/layout/side-bar/signout-btn/index.tsx
  src/constants/mobile/index.ts
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/layout.tsx
  src/mocks/coupon-registration/index.ts
  src/pages/coupon-registration/index.tsx
  src/stores/layout/index.ts
  src/types/layout.ts
Labels: Feat, Style

#186 Feat: 로그인, 회원가입 api 연동
  src/api/index.tsx
  src/api/refresh/index.ts
  src/api/refresh/type.ts
  src/api/sign-in/index.ts
  src/api/sign-up/index.ts
  src/api/sign-up/type.ts
  src/assets/data/refreshData.json
  src/constants/api/index.ts
  src/constants/routes.ts
  src/hooks/sign-in/useSignIn.ts
  src/mocks/accommodation/index.ts
  src/mocks/handlers.ts
  src/mocks/refresh/index.ts
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
  src/test/sign-up/index.tsx
  src/utils/sign-up/ValidateSchema.ts
Labels: Feat

#196 Fix: 쿠폰 도메인 api response 형태 수정
  src/api/coupon/index.ts
  src/assets/data/couponData.json
  src/assets/data/revenueData.json
  src/assets/data/staticsData.json
  src/components/coupon/additional-purchase-footer/index.tsx
  src/components/coupon/additional-purchase-footer/type.ts
  src/hooks/coupon/useCoupon.ts
  src/hooks/main/useMain.ts
  src/mocks/accommodation/index.ts
  src/mocks/coupon/index.ts
  src/mocks/handlers.ts
  src/pages/coupon/index.tsx
  src/queries/coupon/index.ts
Labels: Fix

#191 Feat: 등록 확인 페이지 비즈니스 코드 작성
  src/api/init/index.ts
  src/api/init/type.ts
  src/api/sign-in/index.ts
  src/assets/data/postAccommodationData.json
  src/assets/data/postImageFileData.json
  src/components/init/ButtonContainer.tsx
  src/components/init/init-accommodation-registration/type.ts
  src/components/init/init-info-confirmation/RoomInfo.tsx
  src/components/layout/init-layout/InitLayout.tsx
  src/components/room/price-container/index.tsx
  src/constants/api/index.ts
  src/constants/routes.ts
  src/mocks/init/index.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
  src/pages/sign-in/index.tsx
  src/queries/init/index.ts
  src/queries/sign-in/index.ts
  src/stores/init/atoms.ts
  src/test/sign-in/index.tsx
Labels: Feat

#195 Feat: 로그아웃 서버 api 연동
  src/api/index.tsx
  src/api/refresh/index.ts
  src/api/sign-up/index.ts
  src/assets/data/signInData.json
  src/components/layout/side-bar/signout-btn/index.tsx
  src/hooks/sign-in/useSignIn.ts
  src/pages/sign-in/index.tsx
  src/queries/sign-up/index.ts
  src/utils/refresh/index.ts
Labels: Feat

#199 Chore: 서버 response 데이터 구조가 변함에 따라 수정사항 적용
  src/api/accommodation/index.ts
  src/api/coupon/index.ts
  src/api/point-detail/get-point-detail/index.ts
  src/api/point/index.ts
  src/assets/data/accommodationsData.json
  src/assets/data/couponRoomListData.json
  src/assets/data/pointChargeData.json
  src/assets/data/pointDetailChargesData.json
  src/assets/data/pointDetailData.json
  src/assets/data/pointDetailUsageData.json
  src/assets/data/pointSummaryData.json
  src/components/layout/side-bar/navigation/index.tsx
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/hooks/point-detail/index.tsx
  src/hooks/side-bar/useSideBar.ts
  src/mocks/handlers.ts
  src/pages/point-detail/index.tsx
  src/queries/accommodation/index.ts
  src/queries/coupon-registration/index.ts
  src/queries/point-detail/index.ts
  src/queries/point/index.ts
  src/stores/coupon-registration/atoms.ts
Labels: Chore

#202 Fix: 회원 가입 비밀 번호 유효성 검사 로직 수정
  src/api/index.tsx
  src/components/layout/side-bar/signout-btn/index.tsx
  src/pages/sign-in/index.tsx
  src/utils/sign-up/ValidateSchema.ts
Labels: Fix

#206 Feat: 포인트 요약 조회 API 연결
  src/api/point/index.ts
  src/hooks/point-detail/index.tsx
  src/hooks/side-bar/useSideBar.ts
  src/mocks/handlers.ts
  src/pages/point-detail/index.tsx
  src/queries/point/index.ts
Labels: Feat

#204 Feat: 로그아웃 api 연결
  src/api/logout/index.ts
  src/components/layout/side-bar/signout-btn/index.tsx
  src/pages/sign-in/index.tsx
  src/queries/logout/index.ts
  src/utils/refresh/index.ts
Labels: Feat

#208 Feat: 사이드바 API 핸들링 및 스타일 수정
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/api/point/index.ts
  src/api/point/type.ts
  src/components/coupon-registration/coupon-applier/room-coupon-applier/index.tsx
  src/components/coupon-registration/coupon-preview/coupon-preview-item/index.tsx
  src/components/coupon-registration/coupon-preview/index.tsx
  src/components/coupon-registration/discount-type/index.tsx
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
  src/components/layout/side-bar/user-profile/type.ts
  src/constants/api/index.ts
  src/hooks/coupon-registration/useCouponRegistration.tsx
  src/hooks/side-bar/useSideBar.ts
  src/layout.tsx
  src/queries/coupon-registration/index.ts
  src/queries/point/index.ts
  src/stores/coupon-registration/atoms.ts
  src/stores/point-detail/atoms.ts
Labels: Feat

#211 Style: 객실 카드 스타일 수정 및 객실 중복 로직 추가
  src/api/room/index.ts
  src/api/room/type.ts
  src/components/room/room-card/index.tsx
  src/constants/api/index.ts
  src/pages/init-room-registration/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
  src/queries/room/index.ts
  src/stores/room/atoms.ts
Labels: Style

#209 Feat: 쿠폰 관리 페이지 api 연결
  src/api/coupon/index.ts
  src/api/index.ts
  src/assets/image/userGuideAccommodation.png
  src/assets/image/userGuideCoupon.png
  src/assets/image/userGuideHome.png
  src/assets/image/userGuidePoint.png
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/not-found-coupon/index.tsx
  src/hooks/main/useMain.ts
  src/pages/user-guide/index.tsx
  src/queries/coupon/index.ts
Labels: Feat

#212 Chore: es-lint 오류 제거
  src/hooks/coupon-registration/useCouponRegistration.tsx
Labels: Chore

#207 Refactor: init 플로우 리팩토링
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
  src/utils/init/index.ts
Labels: Refactor

#214 Style: 로그인 화면 퍼블리싱 수정
  src/pages/sign-in/index.tsx
Labels: Style

#216 Style: 이너 스크롤바 제거 및 오타 수정
  src/components/init/ImageUploadContainer.tsx
  src/components/room/room-card/index.tsx
  src/pages/room-management/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
Labels: Style

#217 Fix: 숙소 등록 플로우 버그 수정
  src/api/init/index.ts
  src/components/init/init-accommodation-registration/RadioButtonCustomContainer.tsx
  src/components/init/init-info-confirmation/AccommodationInfo.tsx
  src/components/init/init-info-confirmation/CustomButton.tsx
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/components/layout/init-layout/InitLayout.tsx
  src/mocks/handlers.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
Labels: Fix, Style

#221 Feat: 객실 수정 api 연동
  src/api/accommodation/index.ts
  src/api/room/index.ts
  src/api/room/type.ts
  src/components/init/ImageUploadContainer.tsx
  src/components/room/status-container/index.tsx
  src/pages/room-management/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
  src/queries/room/index.ts
  src/stores/init/type.ts
  src/stores/room/atoms.ts
  src/stores/room/type.ts
Labels: Feat

#220 Fix: 로그인 퍼블리싱 및 회원 가입 border 수정
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
Labels: Fix

#215 Feat: 포인트 API 연결
  src/api/point-detail/get-point-detail/index.ts
  src/api/point-detail/get-point-detail/type.ts
  src/api/point-detail/orderCancel/index.ts
  src/api/point-detail/orderCancel/type.ts
  src/api/toss/index.ts
  src/components/point-detail/index.tsx
  src/components/point-detail/payment/common/order-info/index.tsx
  src/components/point-detail/point-detail-list/index.tsx
  src/components/point-detail/point-detail-menu/index.tsx
  src/index.tsx
  src/pages/point-detail/index.tsx
  src/pages/toss-success/index.tsx
  src/queries/point-charge-modal/index.tsx
  src/queries/point-detail/index.ts
  src/queries/point/index.ts
  src/stores/point-detail/atoms.ts
  src/utils/dateFormat/dateFormat.ts
Labels: Feat

#226 Fix: 특수 문자 제외 정규식 수정
  src/utils/sign-up/ValidateSchema.ts
Labels: Fix

#224 Chore: api 주소 변경사항 적용
  src/api/point/index.ts
Labels: Chore

#223 Refactor: 숙소 등록 플로우 수정
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
Labels: Feat, Refactor

#228 Fix: API URI 및 스타일 수정
  src/api/room/index.ts
  src/components/room/room-card/index.tsx
Labels: Fix

#227 Fix: 포인트 상세내역 조회 데이터바인딩 및 스타일 수정
  src/components/point-detail/payment/common/coupon-info/index.tsx
  src/components/point-detail/payment/common/order-point-info/index.tsx
  src/components/point-detail/point-detail-list/index.tsx
  src/stores/point-detail/atoms.ts
Labels: Fix

#222 Feat: 쿠폰 통계 api 연결
  src/api/coupon/index.ts
  src/api/coupon/type.ts
  src/components/coupon/coupon-header/index.tsx
  src/components/coupon/coupon-status-tag/index.tsx
  src/components/coupon/table/index.tsx
  src/components/main/main-chart/index.tsx
  src/components/main/main-coupon-status-container/index.tsx
  src/components/main/main-coupon-status-container/type.ts
  src/hooks/main/useMain.ts
  src/index.css
  src/pages/main/index.tsx
  src/queries/coupon/index.ts
  src/utils/dateFormat/dateFormat.ts
Labels: Feat

#231 Fix: 객실 refetch 및 toggle error 해결
  src/components/error/ServerError.tsx
  src/components/room/status-container/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
  src/queries/sign-in/index.ts
  src/test/sign-up/SignUp.test.tsx
  src/test/sign-up/index.tsx
  src/utils/sign-up/ValidateSchema.ts
Labels: Fix

#229 Refactor: 숙소 등록 플로우 리팩토링
  src/components/init/ButtonContainer.tsx
  src/components/init/CheckBoxContainer.tsx
  src/components/init/ImageUploadContainer.tsx
  src/components/init/init-info-confirmation/RoomItem.tsx
  src/constants/init/index.ts
  src/pages/init-accommodation-registration/index.tsx
  src/pages/init-info-confirmation/index.tsx
  src/pages/init-room-registration/index.tsx
  src/stores/init/atoms.ts
Labels: Feat, Refactor

#232 Style: antd-btn 기본 border 삭제
  src/components/layout/side-bar/accommodation-list/index.tsx
  src/components/layout/side-bar/user-profile/index.tsx
Labels: Style

#233 Chore: 띄어쓰기 수정
  src/components/main/main-coupon-status-container/index.tsx
Labels: Chore

#234 Fix: 객실 모두 삭제되는 에러 해결
  src/constants/api/index.ts
  src/pages/room-management/index.tsx
  src/queries/room/index.ts
Labels: Fix

#235 Fix: 디자인 및 객실 가격 수정
  src/components/room/price-container/index.tsx
  src/pages/room-management/index.tsx
Labels: Fix

#236 Fix: rafc 형식으로 수정
  src/App.tsx
  src/pages/room-management/index.tsx
  src/pages/room-registration/index.tsx
  src/pages/room-update/index.tsx
Labels: Fix

#239 Fix: 기존 accommodationId 삭제
  src/pages/sign-in/index.tsx
Labels: Fix

#242 Chore: 쿠폰 메세지 더미데이터로 수정
  src/hooks/main/useMain.ts
Labels: Chore

#243 Feature/coupon message
  src/hooks/main/useMain.ts
Labels: Chore

#240 Style: 버튼 border 삭제
  src/components/layout/side-bar/accommodation-list/index.tsx
Labels: Style

#244 Refactor: coupon page 리팩토링
  src/components/domain/coupon/coupon-status-tag/index.tsx
  src/components/domain/coupon/coupon-status-tag/type.ts
  src/components/domain/coupon/table-cell/index.tsx
  src/components/domain/coupon/table-cell/type.ts
  src/components/domain/coupon/table/index.tsx
  src/hooks/coupon/useCoupon.ts
  src/test/coupon/Coupon.test.tsx
Labels: Refactor
